@authToken = {{login.response.body.access}}
@refreshToken = {{login.response.body.refresh}}
# @authToken = {{refreshLogin.response.body.access}}
# @refreshToken = {{refreshLogin.response.body.refresh}}

# @name login
POST {{API_URL}}/login/
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test"
}

###

# @name verifyToken
POST {{API_URL}}/login/verify/
Content-Type: application/json

{
  "token": "{{authToken}}"
}

###

# @name refreshLogin
POST {{API_URL}}/login/refresh/
Content-Type: application/json

{
  "refresh": "{{refreshToken}}"
}

###

# @name listList
GET {{API_URL}}/list/
Authorization: JWT {{authToken}}
Content-Type: application/json

###

# @name listMeasurements
GET {{API_URL}}/measurement/
Authorization: JWT {{authToken}}
Content-Type: application/json

###

